-- SQL para crear la tabla de participantes en Supabase
-- Ejecutar en el SQL Editor de Supabase

CREATE TABLE IF NOT EXISTS participantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT NOT NULL,
    factura TEXT UNIQUE NOT NULL,
    piloto TEXT NOT NULL,
    placa TEXT NOT NULL,
    consumo TEXT,
    empresa TEXT,
    premio TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar permisos de lectura/escritura (Rls - Row Level Security)
-- Por simplicidad, habilitamos acceso público si no tienen autenticación configurada
ALTER TABLE participantes DISABLE ROW LEVEL SECURITY;
